CREATE TABLE IF NOT EXISTS PESSOAS
(
    ID         VARCHAR(36) UNIQUE NOT NULL,
    APELIDO    VARCHAR(1000) UNIQUE,
    NOME       VARCHAR(1000)      NOT NULL,
    NASCIMENTO CHAR(10)           NOT NULL,
    STACK      VARCHAR(4000)      NOT NULL,
    BUSCA_TRGM TEXT GENERATED ALWAYS AS (NOME || APELIDO || STACK) STORED
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PESSOAS_BUSCA_TGRM ON PESSOAS USING GIST (BUSCA_TRGM GIST_TRGM_OPS( SIGLEN= 64));

CREATE EXTENSION PG_TRGM;
